//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2012
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BramkaSMS_GSMService.GSMServiceAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.wso2.org/php", ConfigurationName="GSMServiceAPI.GSMServicePortType")]
    public interface GSMServicePortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.wso2.org/php/xsd) of message GetPriceRequest does not match the default value (http://www.wso2.org/php)
        [System.ServiceModel.OperationContractAttribute(Action="https://api.gsmservice.pl:443/soap/v2/gateway.php/GetPrice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BramkaSMS_GSMService.GSMServiceAPI.GetPriceResponse GetPrice(BramkaSMS_GSMService.GSMServiceAPI.GetPriceRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.wso2.org/php/xsd) of message GetStatusRequest does not match the default value (http://www.wso2.org/php)
        [System.ServiceModel.OperationContractAttribute(Action="http://api.gsmservice.pl/soap/v2/gateway.php/GetStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BramkaSMS_GSMService.GSMServiceAPI.GetStatusResponse GetStatus(BramkaSMS_GSMService.GSMServiceAPI.GetStatusRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.wso2.org/php/xsd) of message GetBalanceRequest does not match the default value (http://www.wso2.org/php)
        [System.ServiceModel.OperationContractAttribute(Action="https://api.gsmservice.pl:443/soap/v2/gateway.php/GetBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BramkaSMS_GSMService.GSMServiceAPI.GetBalanceResponse GetBalance(BramkaSMS_GSMService.GSMServiceAPI.GetBalanceRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.wso2.org/php/xsd) of message CancelRequest does not match the default value (http://www.wso2.org/php)
        [System.ServiceModel.OperationContractAttribute(Action="https://api.gsmservice.pl:443/soap/v2/gateway.php/Cancel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BramkaSMS_GSMService.GSMServiceAPI.CancelResponse Cancel(BramkaSMS_GSMService.GSMServiceAPI.CancelRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.wso2.org/php/xsd) of message SendSMSRequest does not match the default value (http://www.wso2.org/php)
        [System.ServiceModel.OperationContractAttribute(Action="https://api.gsmservice.pl:443/soap/v2/gateway.php/SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BramkaSMS_GSMService.GSMServiceAPI.SendSMSResponse SendSMS(BramkaSMS_GSMService.GSMServiceAPI.SendSMSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.2022")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wso2.org/php/xsd")]
    public partial class Account : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string passField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string pass {
            get {
                return this.passField;
            }
            set {
                this.passField = value;
                this.RaisePropertyChanged("pass");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.2022")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wso2.org/php/xsd")]
    public partial class SendSMSReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string errCodeField;
        
        private string descriptionField;
        
        private string recipientField;
        
        private System.Nullable<int> msgIdField;
        
        private System.Nullable<int> partsField;
        
        private System.Nullable<double> priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("errCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
                this.RaisePropertyChanged("recipient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> msgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
                this.RaisePropertyChanged("msgId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> parts {
            get {
                return this.partsField;
            }
            set {
                this.partsField = value;
                this.RaisePropertyChanged("parts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<double> price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.2022")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wso2.org/php/xsd")]
    public partial class CancelReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string errCodeField;
        
        private string descriptionField;
        
        private System.Nullable<int> msgIdField;
        
        private string recipientField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("errCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> msgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
                this.RaisePropertyChanged("msgId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
                this.RaisePropertyChanged("recipient");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.2022")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wso2.org/php/xsd")]
    public partial class GetBalanceReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string errCodeField;
        
        private string descriptionField;
        
        private System.Nullable<double> balanceField;
        
        private string currencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("errCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<double> balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("balance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.2022")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wso2.org/php/xsd")]
    public partial class GetStatusReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string errCodeField;
        
        private string descriptionField;
        
        private System.Nullable<int> msgIdField;
        
        private string recipientField;
        
        private string origDateField;
        
        private string doneDateField;
        
        private string msgStatusCodeField;
        
        private string msgStatusDescriptionField;
        
        private System.Nullable<int> msgTypeField;
        
        private System.Nullable<int> partsField;
        
        private System.Nullable<double> priceField;
        
        private string extIdField;
        
        private System.Nullable<bool> unicodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("errCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> msgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
                this.RaisePropertyChanged("msgId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
                this.RaisePropertyChanged("recipient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string origDate {
            get {
                return this.origDateField;
            }
            set {
                this.origDateField = value;
                this.RaisePropertyChanged("origDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string doneDate {
            get {
                return this.doneDateField;
            }
            set {
                this.doneDateField = value;
                this.RaisePropertyChanged("doneDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string msgStatusCode {
            get {
                return this.msgStatusCodeField;
            }
            set {
                this.msgStatusCodeField = value;
                this.RaisePropertyChanged("msgStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string msgStatusDescription {
            get {
                return this.msgStatusDescriptionField;
            }
            set {
                this.msgStatusDescriptionField = value;
                this.RaisePropertyChanged("msgStatusDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> msgType {
            get {
                return this.msgTypeField;
            }
            set {
                this.msgTypeField = value;
                this.RaisePropertyChanged("msgType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> parts {
            get {
                return this.partsField;
            }
            set {
                this.partsField = value;
                this.RaisePropertyChanged("parts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<double> price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string extId {
            get {
                return this.extIdField;
            }
            set {
                this.extIdField = value;
                this.RaisePropertyChanged("extId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<bool> unicode {
            get {
                return this.unicodeField;
            }
            set {
                this.unicodeField = value;
                this.RaisePropertyChanged("unicode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.2022")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wso2.org/php/xsd")]
    public partial class GetPriceReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string errCodeField;
        
        private string descriptionField;
        
        private string recipientField;
        
        private System.Nullable<int> partsField;
        
        private System.Nullable<double> priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("errCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
                this.RaisePropertyChanged("recipient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> parts {
            get {
                return this.partsField;
            }
            set {
                this.partsField = value;
                this.RaisePropertyChanged("parts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<double> price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.2022")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wso2.org/php/xsd")]
    public partial class Message : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] recipientsField;
        
        private string messageField;
        
        private string urlField;
        
        private string udhField;
        
        private string senderField;
        
        private System.Nullable<int> msgTypeField;
        
        private System.Nullable<bool> unicodeField;
        
        private System.Nullable<int> timestampField;
        
        private System.Nullable<bool> sandboxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recipients", Order=0)]
        public string[] recipients {
            get {
                return this.recipientsField;
            }
            set {
                this.recipientsField = value;
                this.RaisePropertyChanged("recipients");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string udh {
            get {
                return this.udhField;
            }
            set {
                this.udhField = value;
                this.RaisePropertyChanged("udh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> msgType {
            get {
                return this.msgTypeField;
            }
            set {
                this.msgTypeField = value;
                this.RaisePropertyChanged("msgType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<bool> unicode {
            get {
                return this.unicodeField;
            }
            set {
                this.unicodeField = value;
                this.RaisePropertyChanged("unicode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<bool> sandbox {
            get {
                return this.sandboxField;
            }
            set {
                this.sandboxField = value;
                this.RaisePropertyChanged("sandbox");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPrice", WrapperNamespace="http://www.wso2.org/php/xsd", IsWrapped=true)]
    public partial class GetPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=0)]
        public BramkaSMS_GSMService.GSMServiceAPI.Account account;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("messages")]
        public Message[] messages;
        
        public GetPriceRequest() {
        }
        
        public GetPriceRequest(BramkaSMS_GSMService.GSMServiceAPI.Account account, Message[] messages) {
            this.account = account;
            this.messages = messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPriceResponse", WrapperNamespace="http://www.wso2.org/php/xsd", IsWrapped=true)]
    public partial class GetPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return")]
        public GetPriceReturn[] @return;
        
        public GetPriceResponse() {
        }
        
        public GetPriceResponse(GetPriceReturn[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatus", WrapperNamespace="http://www.wso2.org/php/xsd", IsWrapped=true)]
    public partial class GetStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=0)]
        public BramkaSMS_GSMService.GSMServiceAPI.Account account;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("ids")]
        public string[] ids;
        
        public GetStatusRequest() {
        }
        
        public GetStatusRequest(BramkaSMS_GSMService.GSMServiceAPI.Account account, string[] ids) {
            this.account = account;
            this.ids = ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusResponse", WrapperNamespace="http://www.wso2.org/php/xsd", IsWrapped=true)]
    public partial class GetStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return")]
        public GetStatusReturn[] @return;
        
        public GetStatusResponse() {
        }
        
        public GetStatusResponse(GetStatusReturn[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBalance", WrapperNamespace="http://www.wso2.org/php/xsd", IsWrapped=true)]
    public partial class GetBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=0)]
        public BramkaSMS_GSMService.GSMServiceAPI.Account account;
        
        public GetBalanceRequest() {
        }
        
        public GetBalanceRequest(BramkaSMS_GSMService.GSMServiceAPI.Account account) {
            this.account = account;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBalanceResponse", WrapperNamespace="http://www.wso2.org/php/xsd", IsWrapped=true)]
    public partial class GetBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=0)]
        public BramkaSMS_GSMService.GSMServiceAPI.GetBalanceReturn @return;
        
        public GetBalanceResponse() {
        }
        
        public GetBalanceResponse(BramkaSMS_GSMService.GSMServiceAPI.GetBalanceReturn @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Cancel", WrapperNamespace="http://www.wso2.org/php/xsd", IsWrapped=true)]
    public partial class CancelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=0)]
        public BramkaSMS_GSMService.GSMServiceAPI.Account account;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("ids")]
        public string[] ids;
        
        public CancelRequest() {
        }
        
        public CancelRequest(BramkaSMS_GSMService.GSMServiceAPI.Account account, string[] ids) {
            this.account = account;
            this.ids = ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelResponse", WrapperNamespace="http://www.wso2.org/php/xsd", IsWrapped=true)]
    public partial class CancelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return")]
        public CancelReturn[] @return;
        
        public CancelResponse() {
        }
        
        public CancelResponse(CancelReturn[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMS", WrapperNamespace="http://www.wso2.org/php/xsd", IsWrapped=true)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=0)]
        public BramkaSMS_GSMService.GSMServiceAPI.Account account;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("messages")]
        public Message[] messages;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(BramkaSMS_GSMService.GSMServiceAPI.Account account, Message[] messages) {
            this.account = account;
            this.messages = messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSResponse", WrapperNamespace="http://www.wso2.org/php/xsd", IsWrapped=true)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return")]
        public SendSMSReturn[] @return;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(SendSMSReturn[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GSMServicePortTypeChannel : BramkaSMS_GSMService.GSMServiceAPI.GSMServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GSMServicePortTypeClient : System.ServiceModel.ClientBase<BramkaSMS_GSMService.GSMServiceAPI.GSMServicePortType>, BramkaSMS_GSMService.GSMServiceAPI.GSMServicePortType {
        
        public GSMServicePortTypeClient() {
        }
        
        public GSMServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GSMServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GSMServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GSMServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BramkaSMS_GSMService.GSMServiceAPI.GetPriceResponse BramkaSMS_GSMService.GSMServiceAPI.GSMServicePortType.GetPrice(BramkaSMS_GSMService.GSMServiceAPI.GetPriceRequest request) {
            return base.Channel.GetPrice(request);
        }
        
        public GetPriceReturn[] GetPrice(BramkaSMS_GSMService.GSMServiceAPI.Account account, Message[] messages) {
            BramkaSMS_GSMService.GSMServiceAPI.GetPriceRequest inValue = new BramkaSMS_GSMService.GSMServiceAPI.GetPriceRequest();
            inValue.account = account;
            inValue.messages = messages;
            BramkaSMS_GSMService.GSMServiceAPI.GetPriceResponse retVal = ((BramkaSMS_GSMService.GSMServiceAPI.GSMServicePortType)(this)).GetPrice(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BramkaSMS_GSMService.GSMServiceAPI.GetStatusResponse BramkaSMS_GSMService.GSMServiceAPI.GSMServicePortType.GetStatus(BramkaSMS_GSMService.GSMServiceAPI.GetStatusRequest request) {
            return base.Channel.GetStatus(request);
        }
        
        public GetStatusReturn[] GetStatus(BramkaSMS_GSMService.GSMServiceAPI.Account account, string[] ids) {
            BramkaSMS_GSMService.GSMServiceAPI.GetStatusRequest inValue = new BramkaSMS_GSMService.GSMServiceAPI.GetStatusRequest();
            inValue.account = account;
            inValue.ids = ids;
            BramkaSMS_GSMService.GSMServiceAPI.GetStatusResponse retVal = ((BramkaSMS_GSMService.GSMServiceAPI.GSMServicePortType)(this)).GetStatus(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BramkaSMS_GSMService.GSMServiceAPI.GetBalanceResponse BramkaSMS_GSMService.GSMServiceAPI.GSMServicePortType.GetBalance(BramkaSMS_GSMService.GSMServiceAPI.GetBalanceRequest request) {
            return base.Channel.GetBalance(request);
        }
        
        public BramkaSMS_GSMService.GSMServiceAPI.GetBalanceReturn GetBalance(BramkaSMS_GSMService.GSMServiceAPI.Account account) {
            BramkaSMS_GSMService.GSMServiceAPI.GetBalanceRequest inValue = new BramkaSMS_GSMService.GSMServiceAPI.GetBalanceRequest();
            inValue.account = account;
            BramkaSMS_GSMService.GSMServiceAPI.GetBalanceResponse retVal = ((BramkaSMS_GSMService.GSMServiceAPI.GSMServicePortType)(this)).GetBalance(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BramkaSMS_GSMService.GSMServiceAPI.CancelResponse BramkaSMS_GSMService.GSMServiceAPI.GSMServicePortType.Cancel(BramkaSMS_GSMService.GSMServiceAPI.CancelRequest request) {
            return base.Channel.Cancel(request);
        }
        
        public CancelReturn[] Cancel(BramkaSMS_GSMService.GSMServiceAPI.Account account, string[] ids) {
            BramkaSMS_GSMService.GSMServiceAPI.CancelRequest inValue = new BramkaSMS_GSMService.GSMServiceAPI.CancelRequest();
            inValue.account = account;
            inValue.ids = ids;
            BramkaSMS_GSMService.GSMServiceAPI.CancelResponse retVal = ((BramkaSMS_GSMService.GSMServiceAPI.GSMServicePortType)(this)).Cancel(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BramkaSMS_GSMService.GSMServiceAPI.SendSMSResponse BramkaSMS_GSMService.GSMServiceAPI.GSMServicePortType.SendSMS(BramkaSMS_GSMService.GSMServiceAPI.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public SendSMSReturn[] SendSMS(BramkaSMS_GSMService.GSMServiceAPI.Account account, Message[] messages) {
            BramkaSMS_GSMService.GSMServiceAPI.SendSMSRequest inValue = new BramkaSMS_GSMService.GSMServiceAPI.SendSMSRequest();
            inValue.account = account;
            inValue.messages = messages;
            BramkaSMS_GSMService.GSMServiceAPI.SendSMSResponse retVal = ((BramkaSMS_GSMService.GSMServiceAPI.GSMServicePortType)(this)).SendSMS(inValue);
            return retVal.@return;
        }
    }
}
